spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itechart_group_test_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
liquibase:
  enabled: true
  change-log: classpath:/config/liquibase/test.xml
app:
  jwt:
    secret: qwerty