spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itechart_group_db?autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
liquibase:
  enabled: true
  change-log: classpath:/config/liquibase/dev_vladSyty.xml
app:
  jwt:
    secret: qwerty
logging:
  level:
    com.itechart.trucking: DEBUG