spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itechart_group_db?autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
liquibase:
  enabled: true
  change-log: classpath:/config/liquibase/master.xml
app:
  jwt:
    secret: qwerty
#logging:
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: ${catalina.home}/logs/trucking.log