contexts: ${liquibase.contexts}
changeLogFile: src/main/resources/config/liquibase/test.xml
driver: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/itechart_group_test_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
defaultSchemaName: itechart_group_test_db
username: root
emptyPassword: true
verbose: true
logging: debug
dropFirst: true